version: "3"
services:
  #php-nginx服务
  php-nginx:
    container_name: php-nginx
    image: shanbumin/php:7.1-nginx-alpine3.8
    ports:
      - 8000:80 #测试环境
      - 8001:81 #crm
      - 8002:82 #laravel5.5 scm接口
    volumes:
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./wwwroot/:/var/www/
    working_dir: /var/www
    restart: always
    networks:
       moka:
         ipv4_address: 10.33.0.2
  #php cli模式
  php-cli:
    container_name: php-cli
    image: shanbumin/php:7.1-cli-alpine3.8
    #command: ["tail","-f","/dev/null"]
    command: ["/usr/sbin/crond","-f"]
    working_dir: /var/www
    volumes:
      - ./wwwroot/:/var/www/
    restart: always
    networks:
       moka:
         ipv4_address: 10.33.0.10

#自定义虚拟网络
networks:
  moka:
     driver: bridge
     ipam:
       config:
        - subnet: 10.33.0.0/16
